### ISSUE TITLE
Not downloading from MangaFox

### ISSUE THREAD

**Issue by Jorengarenar** [briefbanane/manga-downloader#10]
Recently I cannot download anything from mangafox.me

The only think what program is doing is this:

```
Retrieving URL list...
done
Catching up to desired chapter...
```

The folder is created, but remain empty

**Comment by briefbanane** [comment]
Thank you for the report.

They made a small change on the site, but now it should work again.
Commit ca6f08635f30aa9cef5eaee3a3b048662644c3b3 should've fixed it.

**Comment by Jorengarenar** [comment]
Thanks for fast fix!

**Comment by Betacentury** [comment]
Thank you!
