### ISSUE TITLE
unable to download via mangafox.me ? could you give an example of link how to download it?

### ISSUE THREAD

**Issue by aakash003** [briefbanane/manga-downloader#11]

**Comment by Jorengarenar** [comment]
It was just fixed, then again...

Well, do you also have:

```
Retrieving URL list...
done
Catching up to desired chapter...
grep: temporary.html: No such file or directory
```
communicat?

**Comment by briefbanane** [comment]
It seems that the connection to mangafox.me is not fully https (anymore), so curl didn't connect to it.
I've added the possibility for the user to allow the insecure connection (commit 36e87d445e89e78ffcbf95aa45371686026f4c57).
If you allow it, it should work again.

**Comment by Jorengarenar** [comment]
Great!
Thank you again!

**Comment by aakash003** [comment]
I switch to http instead of https it worked.
