### ISSUE TITLE
Downloading from MangaHere.co broken

### ISSUE THREAD

**Issue by doersino** [briefbanane/manga-downloader#12]
First of all: Thank you for releasing this.

As the title says, downloading from MangaHere.co doesn't seem to work. More specifically, running the command

```bash
$ ./manga-downloader.sh http://www.mangahere.co/manga/nausica_of_the_valley_of_the_wind/v002/c001/
Retrieving URL list...
done
Catching up to desired chapter...
```

fails with the output shown, only resulting in an empty directory `nausica_of_the_valley_of_the_wind` being created.

I'd be grateful if you could take a look at what's going wrong there.

**Comment by briefbanane** [comment]
Thanks for the report!

There was a small change on their site, 33752609cba9e13ef47f9af39a82ba34c1d17b7e should fix it.

**Comment by doersino** [comment]
Awesome, thank you! 🎉
