### ISSUE TITLE
"All chapters (0) downloaded" from mangareader.net

### ISSUE THREAD

**Issue by catthou** [briefbanane/manga-downloader#17]
The script keeps detecting zero chapters, when clearly there are more.
I first tried it on [Yokohama](https://www.mangareader.net/yokohama-kaidashi-kikou) , then [Naruto](https://www.mangareader.net/naruto) then on pages inside the mangas, and even with an http link instead of https, but nothing worked.

`haruka@harukde:~$ ./manga-downloader.sh https://www.mangareader.net/yokohama-kaidashi-kikou`
`All chapters (0) downloaded`
`haruka@harukde:~$ ./manga-downloader.sh https://www.mangareader.net/yokohama-kaidashi-kikou/1`
`All chapters (0) downloaded`
`haruka@harukde:~$ ./manga-downloader.sh https://www.mangareader.net/yokohama-kaidashi-kikou/1/1`
`All chapters (0) downloaded`
`haruka@harukde:~$ ./manga-downloader.sh http://www.mangareader.net/yokohama-kaidashi-kikou`
`All chapters (0) downloaded`

**Comment by briefbanane** [comment]
Thank you for reporting. The script internally used http requests, but it seems like the site doesn't like them anymore. I switched to https 12d1333361c2d4bdaf2871dbfca5897beb957cf8, which should do the trick.

**Comment by catthou** [comment]
An excellent update. Working as expected again.
