### ISSUE TITLE
Fanfox.net broken again?

### ISSUE THREAD

**Issue by catthou** [briefbanane/manga-downloader#18]
It seems fanfox downloading is broken again, I tried on:
https://fanfox.net/manga/reverie_in_a_deserted_bus/

```
$ ./manga-downloader.sh https://fanfox.net/manga/reverie_in_a_deserted_bus/
Retrieving URL list...
done
Catching up to desired chapter...
```
and from the chapter itself:
```
$ ./manga-downloader.sh https://fanfox.net/manga/reverie_in_a_deserted_bus/c002/1.html
Retrieving URL list...
done
Catching up to desired chapter...
```

Using Linux Mint 19.1

**Comment by briefbanane** [comment]
Yes, you're right. They started using JavaScript to load images. There probably is no predictable naming scheme anymore or at least not an easy one.
I'll remove it from the supported list. If somebody figures out a way to handle it, please make a pull request.
