### ISSUE TITLE
Support http://juinjutsuteam.netsons.org/

### ISSUE THREAD

**Issue by Betacentury** [briefbanane/manga-downloader#3]
while i was downloading slayers from mangapanda i got this message

$manga-downloader.sh http://www.mangapanda.com/1121-40980-1/slayers-light-magic/chapter-2.html
This shouldn't happen. Please try again and if it still fails, report a bug at github.com/briefbanane/manga-downloader
and include the last URL: http://www.mangapanda.com/slayers-light-magic/2/1 image-URL: http://i16.mangapanda.com/slayers-light-magic/2/slayers-light-magic-1019412.jpg and curl-return: 33

**Comment by briefbanane** [comment]
Did you already retry? There are many cases where the problem comes from an instable connection or some temporary server problem. (curl-return: 33 means the HTTP range command didn't work, which normally shouldn't happen).

Otherwise try deleting the image file first and then test again.

**Comment by Betacentury** [comment]
Yesterday I tried many times, without success, but today it works fine, maybe my connection was faulty.

I take this opportunity to thank you for the project and suggest support for this website:
http://juinjutsuteam.netsons.org/

**Comment by briefbanane** [comment]
Good to hear that. Maybe it wasn't your connection but the servers fault. The script currently only recognizes a problem, but doesn't figure out where it comes from. (Maybe I will add a bit of that in the future, don't know how complex that would be)

You're welcome, I'll see what I can do for that website.

**Comment by briefbanane** [comment]
I haven't tested it extensively, but with my new commit ce41c7b5ea67f4b80febf6dd65cd1ba2d79d16c2 it seems to work.
