### ISSUE TITLE
Can't catch to desired chapter

### ISSUE THREAD

**Issue by Dr4mEdo** [briefbanane/manga-downloader#9]
Hey, thanks for the fix about tac,

Mangafox is working very well ^^, but (there always a but :p), when I'm trying the script for japscan it doesn't seem to catch the chapter, I tryied with different chapter/manga and it doesn't work :/

Here is my logs :

>  JeanJean:~ Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://mangafox.me/manga/soul_cartel/v01/c216/1.html
> Retrieving URL list...
> done
> Catching up to desired chapter...
> Downloading chapter 216 of volume 01
> Page #1 of chapter #216 downloaded
> Page #2 of chapter #216 downloaded
> Page #3 of chapter #216 downloaded
> Page #4 of chapter #216 downloaded
> Page #5 of chapter #216 downloaded
> Page #6 of chapter #216 downloaded
> Page #7 of chapter #216 downloaded
> Page #8 of chapter #216 downloaded
> Page #9 of chapter #216 downloaded
> Page #10 of chapter #216 downloaded
> Page #11 of chapter #216 downloaded
> Page #12 of chapter #216 downloaded
> Page #13 of chapter #216 downloaded
> Page #14 of chapter #216 downloaded
> Page #15 of chapter #216 downloaded
> Page #16 of chapter #216 downloaded
> Page #17 of chapter #216 downloaded
> Page #18 of chapter #216 downloaded
> Page #19 of chapter #216 downloaded
> Page #20 of chapter #216 downloaded
> Page #21 of chapter #216 downloaded
> Page #22 of chapter #216 downloaded
> Page #23 of chapter #216 downloaded
> Page #24 of chapter #216 downloaded
> Page #25 of chapter #216 downloaded
> Page #26 of chapter #216 downloaded
> Page #27 of chapter #216 downloaded
> Page #28 of chapter #216 downloaded
> All pages (28) of chapter #216 downloaded
> JeanJean:~ Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://www.japscan.com/lecture-en-ligne/ultimate-antihero/6/
> Retrieving URL list...
> done
> Catching up to desired chapter...
> JeanJean:~ Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://www.japscan.com/mangas/ultimate-antihero/
> Retrieving URL list...
> done
> Catching up to desired chapter...
> Downloading volume/chapter 
> All pages (0) of chapter/volume # downloaded
> JeanJean:~ Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
> Retrieving URL list...
> done
> Catching up to desired chapter...
> JeanJean:~ Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://www.japscan.com/lecture-en-ligne/naruto/700.1/
> Retrieving URL list...
> done
> Catching up to desired chapter...
> JeanJean:~ Admin$

**Comment by briefbanane** [comment]
Strange, for me it works. Probably it's another incompatibility between Linux and OSX. Could you please run the script with
`bash -x  /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh "http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/"`
Hopefully this will allow me to see what's going on.

**Comment by Dr4mEdo** [comment]
Here it is : 

`bash -x /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh "http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/"
+ url=http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
+ '[' '!' http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/ ']'
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ grep -E '^https?://'
+ '[' '!' http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/ ']'
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ cut -d / -f 3
+ base=www.japscan.com
+ case $base in
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ grep -E '^https?://www.japscan.com/lecture-en-ligne/[^/]*/[^/]*/'
+ '[' http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/ ']'
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ cut -d / -f 5
+ manganame=ultimate-antihero
+ mkdir -p ultimate-antihero
+ cd ultimate-antihero
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ cut -d / -f 6
+ subcategory=1
+ found=0
+ echo 'Retrieving URL list...'
Retrieving URL list...
+ rm -f temporary2.html
++ echo http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/
++ cut -d / -f 1-3
+ download http://www.japscan.com/mangas/ultimate-antihero/ temporary2.html
+ curlreturn=18
+ '[' 18 -eq 18 ']'
+ curl -s -A 'Mozilla/5.0 (X11; Linux x86_64; rv:23.0)' --compressed --max-redirs 0 http://www.japscan.com/mangas/ultimate-antihero/ -o temporary2.html -C -
+ curlreturn=0
+ '[' 0 -eq 18 ']'
+ sed 's/<a/\n&/g' temporary2.html
+ echo done
done
+ echo 'Catching up to desired chapter...'
Catching up to desired chapter...
+ grep -E 'href="//www.japscan.com/lecture-en-ligne/ultimate-antihero/[^/]*/"' temporary.html
+ cat temporary2.html
+ awk '{split($0,a,"href");$1=a[2];print $1}'
+ awk '{split($0,a,"\"");$1=a[2];print "http:"$1"1.html"}'
+ rm -f temporary2.html
++ tac_awk temporary.html
++ cat temporary.html
++ awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }'
+ for word in '`tac_awk temporary.html`'
+ '[' 0 -ne 1 ']'
++ echo http://cdn.japscan.com/css/main.css1.html
++ grep -E 'https?://www.japscan.com/lecture-en-ligne/[^/]*/1/[0-9]*.html'
+ '[' ']'
+ '[' 0 -eq 1 ']'
+ rm -f temporary.html`

**Comment by briefbanane** [comment]
Something seems to be different in the HTML files or with how the get processed. Could you please apply this patch http://pastebin.com/raw/USGLXxCc and post the output. (Just copy/paste it into a file new.patch and run the command
`patch manga-downloader.sh new.patch`
inside the directory with the script-file.) Then run
` /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh "http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/" > contents.log`
and post the contents of the logfile on http://pastebin.com because it's going to be relatively long.

**Comment by Dr4mEdo** [comment]
Hum, the patch command doesn’t seem to work properly…

"manga-downloader-master Admin$ patch manga-downloader.sh new.patch
patching file manga-downloader.sh
Hunk #1 FAILED at 744.
1 out of 1 hunk FAILED -- saving rejects to file manga-downloader.sh.rej
Jean-Jean:manga-downloader-master Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh "http://www.japscan.com/lecture-en-ligne/ultimate-antihero/1/" > contents.log »

and the contents.log is a bit empty ^^ :
	"	Retrieving URL list... done Catching up to desired chapter…  "

**Comment by briefbanane** [comment]
If the patch didn't apply it's clear that the log will be empty. Here's a copy of the modified script: http://pastebin.com/raw/ysCivm7g Please use that one and hopefully the log will be fuller ;)

**Comment by Dr4mEdo** [comment]
Here it is :

http://pastebin.com/raw/scgZ5KM7 <http://pastebin.com/raw/scgZ5KM7>

**Comment by briefbanane** [comment]
Thanks again for testing. I think the problem was the `\n` in the sed command. This commit 2a7e57663a029853d23621ac3a0968cb019dc4c6 should fix it. Please download the latest version and tell me if that works.

**Comment by Dr4mEdo** [comment]
No problems^^

Everything is woking fine, thanks !!!

 I can download the chapters ! But (still^^) imagemagick can’t use correctly its montage command 
	"Admin$ /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh http://www.japscan.com/lecture-en-ligne/naruto/710/
Retrieving URL list...
done
Catching up to desired chapter...
Downloading volume/chapter 710
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #1 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #2 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #3 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #4 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #5 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #6 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #7 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #8 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #9 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #10 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #11 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #12 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #13 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #14 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #15 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #16 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #17 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #18 of chapter/volume #710 downloaded
montage: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1315.
Page #19 of chapter/volume #710 downloaded
All pages (0) of chapter/volume #710 downloaded »

So the image are still mess up :/
Imagemagick has been install via home brew ;)

**Comment by briefbanane** [comment]
Good to hear that it kinda works :) At least the problem isn't in the script any more.

It seems that ImageMagick needs ghostscript to properly montage the image (I did a quick google search with the error message: https://stackoverflow.com/questions/13936256/imagemagick-error-while-running-convert-convert-unable-to-read-font) And maybe that's the same problem: https://stackoverflow.com/questions/1014506/imagemagickerror-unable-to-read-font-null-null

I can't really help you more than that, because I don't have OS X. Could you please tell me if installing ghostscript works around the remaining issue, so I can specify that as another requirement in the ReadMe

**Comment by Dr4mEdo** [comment]
I just install ghostscript through home-brew and … no more errors !! But the page is still messed up ^^ 

	http://imgur.com/Yr5wtD6 <http://imgur.com/Yr5wtD6>

**Comment by briefbanane** [comment]
It's still messed up, but in another way (and again on my system it works fine, possibly yet another incompatibility). Here is the scrambled picture on the japscan server: http://cdn.japscan.com/cr-images/Naruto/710/06.jpg which is clearly different.

Would you please run the script with `bash -x /Users/Admin/Desktop/manga-downloader-master/manga-downloader.sh "http://www.japscan.com/lecture-en-ligne/naruto/710/" > contents.log` again and post the probably long logfile on http://pastebin.com

**Comment by briefbanane** [comment]
73d662a6dd3c34ed89c38baeea67174d3e368603 I think I found the faulty command: `ls -v` does something different on Linux then on OS X/BSD.
Please test again with the latest version. I really hope that it works now.

**Comment by Dr4mEdo** [comment]
Yeeeaaaahhhhh !! Every is working smooth !!!


Thanks a lot, for your time and effort !

**Comment by briefbanane** [comment]
You're welcome. All I can say is that I learned a lot in the process ;)
